project:
  type: website
  render:
    - index.qmd
    - speakers.qmd

website:
  title: "CMB 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - speakers.qmd
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Registration is open** - [Apply here](https://forms.gle/DyJdW7J8uFJ4iPoA6) before **May 1st 2025!**"
  #   type: primary
  #   position: below-navbar
format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.css
    toc: true

theme:
  light: flatly
  dark: darkly

